AllCops: 
  NewCops: enable

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SymbolArray:
  Enabled: false